name = "TimeseriesFeatures"
uuid = "f3112013-b923-4dfa-b867-8806c885f823"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com> and contributors"]
version = "0.7.0"

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MoreMaps = "d6ea422f-1f55-4be1-bfc3-e7c09aa4d855"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Associations = "614afb3a-e278-4863-8805-9959372b9ec2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"

[extensions]
StatsBaseExt = ["StatsBase"]
TimeseriesToolsExt = ["TimeseriesTools", "StatsBase"]

[compat]
Associations = "4"
DimensionalData = "0.19 - 0.29"
MoreMaps = "0.2.1"
ProgressLogging = "0.1"
Requires = "1"
Statistics = "1"
StatsBase = "0.30 - 0.34"
TimeseriesTools = "0.6.1"
julia = "1.10"

[extras]
Associations = "614afb3a-e278-4863-8805-9959372b9ec2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"
